---
title: "ELISA_titers"
author: "Marcos Vieira"
date: "10/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(readr)
library(stringr)
library(dplyr)
library(scales)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())
source('gene_frequency_functions.R')
```

```{r}
titers <- read_csv('../data/ELISA_titers.csv')

titers <- get_info_from_mouse_id(titers) %>%
  mutate(group_controls_pooled = factor(group_controls_pooled, levels = group_controls_pooled_factor_levels))


# For plotting, set titers below measurement threshold as 0
titers <- titers %>% 
  mutate(titer = ifelse(str_detect(titer, '<'), 0, as.integer(titer)))
  
titers %>% 
  ggplot(aes(x = group_controls_pooled, y = titer, color = infection_status)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point(position = position_jitter(width = 0.2, height = 0)) +
  scale_y_log10(oob = scales::squish_infinite) +
  facet_grid(antigen~., scales = 'free') +
  background_grid()

titers_against_NL09 <- titers %>% 
  filter(antigen == "NL09_whole_virus") %>%
  ggplot(aes(x = group_controls_pooled, y = titer, color = infection_status)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point(position = position_jitter(width = 0.2, height = 0),
             size = 3, alpha =0.8) +
  scale_y_log10(oob = scales::squish_infinite,
                labels=trans_format('log10',math_format(10^.x))) + 
  background_grid() +
  geom_hline(yintercept = -100, linetype =2) +
  ylab('IgG ELISA titer against the infecting strain') +
  xlab('Group')
plot(titers_against_NL09)

save(titers_against_NL09,
     file = '../figures/all_seqs_freqs/exported_ggplot_objects/titers.RData')

```



```{r}
titers %>% 
  filter(antigen == "NL09_whole_virus") %>%
  ggplot(aes(x = group_controls_pooled, y = titer, color = infection_status)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_text(aes(label = mouse_id), position = position_jitter(width = 0.3, height = 0),
             size = 3, alpha =0.8) +
  scale_y_log10(oob = scales::squish_infinite,
                labels=trans_format('log10',math_format(10^.x))) + 
  background_grid() +
  geom_hline(yintercept = -100, linetype =2) +
  ylab('IgG ELISA titer against the infecting strain') +
  xlab('Group')
```

