library(dplyr)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())


# Functions for simulating the recruitment, competition and evolution of B cell lineages in GCs
# While keeping track of V allele usage and clone's identities

# Three types of alleles, with gamma distributions for their possible affinites
# Alleles with low affinity overall
n_low_alleles <- 10
low_affinity_alphas <- 1.5 + rnorm(n_low_alleles,0, 0)
low_affinity_betas <- 1 + rnorm(n_low_alleles,0,0)

# Alleles with high average affinity
n_high_avg_alleles <- 5 
high_avg_alphas <- 10 + rnorm(n_high_avg_alleles,0, 0)
high_avg_betas <-  2 + rnorm(n_high_avg_alleles,0,0)

# Alleles with intermediate average but long tails
n_long_tail_alleles <- 2
long_tail_alphas <- 2 + rnorm(n_long_tail_alleles, 0, 0)
long_tail_betas <- 0.5 + rnorm(n_long_tail_alleles,0, 0)

total_n_allelles <- n_low_alleles + n_high_avg_alleles + n_long_tail_alleles

affinity_distribution_parameters <- 
  tibble(allele = paste0('V', 1:total_n_allelles),
         allele_type = c(rep('low', n_low_alleles),
                         rep('high average', n_high_avg_alleles),
                         rep('long-tail', n_long_tail_alleles)),
         alpha = c(low_affinity_alphas, high_avg_alphas, long_tail_alphas),
         beta = c(low_affinity_betas, high_avg_betas, long_tail_betas),
         ) %>%
  mutate(expected_affinity = alpha / beta)

affinity_distribution_parameters %>%
  ggplot(aes(x = allele_type, y = expected_affinity)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point()
  
  
  
full_join(tibble(x = seq(0,15,0.1)),
          affinity_distribution_parameters, by = character()) %>%
  select(allele, allele_type, alpha, beta, x) %>%
  mutate(density = dgamma(x = x, shape = alpha, rate = beta)) %>%
  ggplot(aes(x = x, y = density, group = allele)) +
  geom_line(aes(color = allele_type)) +
  theme(legend.position = 'none')


full_join(tibble(x = seq(0,15,0.1)),
          affinity_distribution_parameters, by = character()) %>%
  select(allele, allele_type, alpha, beta, x) %>%
  mutate(density = dgamma(x = x, shape = alpha, rate = beta)) %>%
  ggplot(aes(x = x, y = density, group = allele)) +
  geom_line(aes(color = allele_type)) +
  theme(legend.position = 'none') +
  scale_y_log10()



load('~/Desktop/v_gene_selection/results/precomputed_gene_freqs_all_seqs.RData')





# A number of distributions equal to n_V_alleles is generated by randomly sampling the k and theta
# parameters for each allele


